CREATE TABLE IF NOT EXISTS tickets (
	code		BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	firstname	VARCHAR(50) NOT NULL,
	lastname	VARCHAR(50) NOT NULL,
	street		VARCHAR(50) NOT NULL,
	housenumber	VARCHAR(5) NOT NULL,
	postalcode	INT(5) UNSIGNED NOT NULL,
	town		VARCHAR(50) NOT NULL,
	date		TIMESTAMP NOT NULL,
	used		BOOLEAN NOT NULL DEFAULT false,
	PRIMARY KEY (code)
);